name: fileshare-app
base: core22
version: '1.0.0'
summary: Share files over WiFi
description: |
  Share files between your computer and mobile devices securely over WiFi.

grade: stable
confinement: strict

apps:
  fileshare-app:
    command: bin/fileshare
    plugs: [network, network-bind, home]

parts:
  fileshare:
    plugin: dump
    source: releases/linux/
    organize:
      fileshare: bin/fileshare
